name: "Dryrun TIH bot"
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  dryrun-tih-bot:
    strategy:
      fail-fast: false
      # Linux runner
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Dryrun bot"
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}/
          make install
          TIH_DRYRUN=1 ./twitbot-tih-run.sh
