# PyLint
name: "pylint"
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  pylint:
    name: "Python Linting"
    strategy:
      fail-fast: false
      # Linux runner
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install pylint on Ubuntu"
        run: |
          sudo apt update
          sudo apt install pylint -y

      - name: "Run pylint"
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}/
          pylint --version
          make install
          source ./venv
          for f in $(find . \( -path ./.git -o -path ./tih_venv \) -prune -o -type f -print); do
            if file "$f" | grep "Python script" &>/dev/null; then
              pylint "$f"
            fi
          done
