# Shell script linting
name: "Shellcheck"
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  shellcheck:
    name: "shellcheck"
    strategy:
      fail-fast: false
      # Linux runner
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install shellcheck on Ubuntu"
        run: |
          sudo apt update
          sudo apt install shellcheck -y

      - name: "Run shellcheck"
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}/
          shellcheck --version
          for f in $(find . -path ./.git -prune -o -type f -print); do
            if file "$f" | grep "shell script" &>/dev/null; then
              shellcheck "$f"
            fi
          done
